=== IRNAS/UsefulSource/usefulsource_example/example-schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema elementFormDefault="qualified" version="1" xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="project" type="typeProject"/>
    <xs:complexType name="typeProject">
      <xs:sequence>
        <xs:element name="unit" type="typeUnit"/>
        <xs:element name="physical_parts" type="typephysical_parts" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>

<xs:element name="unit" type="typeUnit"/>
    <xs:complexType name="typeUnit">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="description" type="typeDescription"/>
            <xs:element name="video" type="typeVideo" minOccurs="0"/>
            <xs:element name="image" type="xs:normalizedString" minOccurs="0"/>
            <xs:element name="logic_parts" type="typeLogic_parts" minOccurs="0"/>
            <xs:element name="assembly_instruction" type="typeAssembly_instruction" minOccurs="0"/>
            <xs:element name="test_instruction" type="typeTest_instruction" minOccurs="0"/>
            <xs:element name="user_manual" type="typeUser_manual" minOccurs="0"/>
            <xs:element name="licensing" type="typeLicensing" minOccurs="0"/>
            <xs:element name="safety" type="typeSafety" minOccurs="0"/>
            <xs:element name="children" type="typeChildren" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="order" type="xs:positiveInteger"/>
    </xs:complexType>
    
    <xs:complexType name="typeChildren">
        <xs:all>
            <xs:element name="unit" type="typeUnit" minOccurs="0" maxOccurs="unbounded"/>
        </xs:all>
    </xs:complexType>
    
    
    <xs:complexType name="typeDescription">
        <xs:all>
            <xs:element name="abstract" type="xs:string" minOccurs="0"/>
            <xs:element name="long_description" type="xs:string" minOccurs="0"/>
            <xs:element name="what" type="xs:string" minOccurs="0"/>
            <xs:element name="why" type="xs:string" minOccurs="0"/>
            <xs:element name="how" type="xs:string" minOccurs="0"/>
            <xs:element name="tags" type="typeTags" minOccurs="0"/>
        </xs:all>
    </xs:complexType>
    
    <xs:complexType name="typeTags">
        <xs:all>
            <xs:element name="tag" type="xs:string" maxOccurs="unbounded"/>
        </xs:all>
    </xs:complexType>
    
    <xs:complexType name="typeVideo">
        <xs:all>
            <xs:element name="description" type="xs:token" minOccurs="0"/>
            <xs:element name="url" type="xs:normalizedString" minOccurs="0"/>
        </xs:all>
    </xs:complexType>
    
    <xs:complexType name="typeLogic_parts">
        <xs:sequence>
            <xs:element name="logic_part" type="typeLogic_part" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="typeLogic_part">
        <xs:all>
            <xs:element name="name" type="xs:string" minOccurs="0"/>
            <xs:element name="description" type="xs:string" minOccurs="0"/>
            <xs:element name="quantity" type="xs:positiveInteger" minOccurs="0"/>
            <xs:element name="image" type="xs:normalizedString" minOccurs="0"/>
            <xs:element name="designator" type="xs:string" minOccurs="0"/>
            <xs:element name="digital_part" type="typeDigital_part" minOccurs="0"/>
            <xs:element name="physical_part_tags" type="typePart_tags" minOccurs="0"/>
            <xs:element name="logic_part_tag" type="xs:normalizedString" minOccurs="0"/>
        </xs:all>
    </xs:complexType>

    <xs:complexType name="typeDigital_part">
        <xs:all>
            <xs:element name="file" type="xs:normalizedString" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="url" type="xs:normalizedString" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="parameters" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
        </xs:all>
    </xs:complexType>
    
    <xs:complexType name="typePart_tegs">
        <xs:all>
           <xs:element name="part_tag" type="xs:normalizedString" maxOccurs="unbounded"/>
        </xs:all>
    </xs:complexType>

    <xs:complexType name="typeAssembly_instruction">
        <xs:all>
            <xs:element name="step" type="typeStep" maxOccurs="unbounded"/>
        </xs:all>
    </xs:complexType>
    
    <xs:complexType name="typeTest_instruction">
        <xs:all>
            <xs:element name="step" type="typeStep" maxOccurs="unbounded"/>
        </xs:all>
    </xs:complexType>
    
    <xs:complexType name="typeUser_manual">
        <xs:all>
            <xs:element name="step" type="typeStep" maxOccurs="unbounded"/>
        </xs:all>
    </xs:complexType>
    
    
    <xs:complexType name="typeStep">
        <xs:all>
            <xs:element name="description" type="xs:string" minOccurs="0"/>
            <xs:element name="video" type="typeVideo" minOccurs="0"/>
            <xs:element name="image" type="xs:normalizedString" minOccurs="0"/>
            <xs:element name="logic_part_tags" type="typePart_tags" minOccurs="0"/>
        </xs:all>
    </xs:complexType>
    
    <xs:complexType name="typeLicensing">
        <xs:all>
            <xs:element name="description" type="xs:string" minOccurs="0"/>
            <xs:element name="file" type="xs:normalizedString" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="url" type="xs:normalizedString" minOccurs="0" maxOccurs="unbounded"/>
        </xs:all>
    </xs:complexType>
    
    <xs:complexType name="typeSafety">
        <xs:all>
            <xs:element name="description" type="xs:string" minOccurs="0"/>
            <xs:element name="file" type="xs:normalizedString" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="url" type="xs:normalizedString" minOccurs="0" maxOccurs="unbounded"/>
        </xs:all>
    </xs:complexType>
    
    <xs:complexType name="typephysical_parts">
        <xs:sequence>
            <xs:element name="physical_part" type="typephysical_part" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="typephysical_part">
        <xs:all>
            <xs:element name="description" type="xs:string"  minOccurs="0"/>
            <xs:element name="name" type="xs:string" minOccurs="0"/>
            <xs:element name="supplier" type="xs:string" minOccurs="0"/>
            <xs:element name="supplier_number" type="xs:normalizedString"  minOccurs="0"/>
            <xs:element name="manufacturer_number" type="xs:normalizedString"  minOccurs="0"/>
            <xs:element name="url" type="xs:normalizedString" minOccurs="0"/>
            <xs:element name="physical_part_tag" type="xs:normalizedString" minOccurs="0"/>
        </xs:all>
    </xs:complexType>
    
</xs:schema>

=== IRNAS/UsefulSource/usefulsource_example/example.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="example.xsl"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="example-schema.xsd" xmlns:xlink="http://www.w3.org/1999/xlink">
  <unit>
    <name>SYSTEM NAME</name>
    <description>
      <abstract>
    Very brief description of the system.
    </abstract>
      <long_description/>
      <what>
    Specific short description of what the system does, 100 words limited.
    </what>
      <why>
    Specific short description of why the system is used/ what problem it solves and how much it might reduce costs, 100 words limited.
    </why>
      <how>
     Specific short description of how the functionality is achieved or one can reproduce it, 100 words limited.
    </how>
      <tags>
        <tag>Tag1</tag>
        <tag>Tag2</tag>
        <tag>Tag3</tag>
      </tags>
    </description>
    <video>
      <description>Intro video</description>
      <url>http://www.youtube.com/embed/yq6hBNCzH10</url>
    </video>
    <image/>
    <logic_parts>
      <logic_part>
        <name>Logic part 1</name>
        <description>Destcription of first logic part of the system.</description>
        <quantity>3</quantity>
        <image/>
        <designator>Designator for Logic part 1.</designator>
        <digital_part>
          <file>example.txt</file>
          <url>http://www.irnas.eu</url>
          <parameters>example.txt</parameters>
        </digital_part>
        <physical_part_tags>
          <part_tag>physical_part1</part_tag>
          <part_tag>physical_part2</part_tag>
        </physical_part_tags>
        <logic_part_tag>logic_part1</logic_part_tag>
      </logic_part>
      <logic_part>
        <name>Logic part 2</name>
        <description>Destcription of the second logic part of the system.</description>
        <quantity>10</quantity>
        <image/>
        <designator>Designator for Logic part 2.</designator>
        <digital_part>
          <file>example.txt</file>
          <url>http://www.irnas.eu</url>
          <parameters>example.txt</parameters>
        </digital_part>
        <physical_part_tags>
          <part_tag>physical_part1</part_tag>
          <part_tag>physical_part2</part_tag>
        </physical_part_tags>
        <logic_part_tag>logic_part2</logic_part_tag>
      </logic_part>
    </logic_parts>
    <assembly_instruction>
      <step>
        <description>Step 1 instructions for the whole system.</description>
        <image>img/img1.jpg</image>
        <video/>
        <logic_part_tags>
          <part_tag>logic_part1</part_tag>
          <part_tag>logic_part2</part_tag>
        </logic_part_tags>
      </step>
      <step>
        <description>Step 2 instructions for the whole system.</description>
        <image>img/img1.jpg</image>
        <video/>
        <logic_part_tags>
          <part_tag>logic_part1</part_tag>
          <part_tag>logic_part2</part_tag>
        </logic_part_tags>
      </step>
    </assembly_instruction>
    <test_instruction>
      <step>
        <description>Step 1 instructions on how to test the whole system.</description>
        <image>img/img1.jpg</image>
        <video/>
        <logic_part_tags>
          <part_tag>logic_part1</part_tag>
          <part_tag>logic_part2</part_tag>
        </logic_part_tags>
      </step>
      <step>
        <description>Step 2 instructions on how to test the whole system.</description>
        <image>img/img1.jpg</image>
        <video/>
        <logic_part_tags>
          <part_tag>logic_part1</part_tag>
          <part_tag>logic_part2</part_tag>
        </logic_part_tags>
      </step>
    </test_instruction>
    <user_manual>
      <step>
        <description>Step 1 in user manual on how to use the whole system.</description>
        <image>img/img1.jpg</image>
        <video/>
        <logic_part_tags>
          <part_tag>logic_part1</part_tag>
          <part_tag>logic_part2</part_tag>
        </logic_part_tags>
      </step>
      <step>
        <description>Step 2 in user manual on how to use the whole system.</description>
        <image>img/img1.jpg</image>
        <video/>
        <logic_part_tags>
          <part_tag>logic_part1</part_tag>
          <part_tag>logic_part2</part_tag>
        </logic_part_tags>
      </step>
    </user_manual>
    <licensing>
      <description>Licensing for the whole system.</description>
      <file>example.txt</file>
      <url>http://www.irnas.eu</url>
    </licensing>
    <safety>
      <description>Safety for the whole system.</description>
      <file>example.txt</file>
      <url>http://www.irnas.eu</url>
    </safety>
    
    <children>
      <unit order="1">
        <name> UNIT1</name>
        <description>
          <abstract>
            Very brief description of the first unit (module).
            </abstract>
          <long_description>
           Description of the first unit (module).
          </long_description>
          <what>
            Specific short description of what the unit 1 does, 100 words limited.
            </what>
          <why>
            Specific short description of why the unit 1 is used/ what problem it solves and how much it might reduce costs, 100 words limited.
            </why>
          <how>
             Specific short description of how the functionality is achieved or one can reproduce it, 100 words limited.
            </how>
          <tags>
            <tag>Tag1</tag>
            <tag>Tag2</tag>
            <tag>Tag3</tag>
          </tags>
        </description>
         <video>
      <description>Intro video</description>
      <url>http://www.youtube.com/embed/yq6hBNCzH10</url>
    </video>
        <image>img1.jpg</image>
        <logic_parts>
          <logic_part>
            <name>Logic part 3</name>
            <description>Destcription of first logic part of the unit 1.</description>
            <quantity>3</quantity>
            <image/>
            <designator>Designator for Logic part 3.</designator>
            <digital_part>
              <file>example.txt</file>
              <url>http://www.irnas.eu</url>
              <parameters>example.txt</parameters>
            </digital_part>
            <physical_part_tags>
              <part_tag>physical_part1</part_tag>
              <part_tag>physical_part2</part_tag>
            </physical_part_tags>
            <logic_part_tag>logic_part3</logic_part_tag>
          </logic_part>
          <logic_part>
            <name>Logic part 4</name>
            <description>Destcription of the second logic part of the unit 1.</description>
            <quantity>10</quantity>
            <image/>
            <designator>Designator for Logic part 4.</designator>
            <digital_part>
              <file>example.txt</file>
              <url>http://www.irnas.eu</url>
              <parameters>example.txt</parameters>
            </digital_part>
            <physical_part_tags>
              <part_tag>physical_part1</part_tag>
              <part_tag>physical_part2</part_tag>
            </physical_part_tags>
            <logic_part_tag>logic_part4</logic_part_tag>
          </logic_part>
        </logic_parts>
        <assembly_instruction>
          <step>
            <description>Step 1 instructions for the unit 1.</description>
            <image>img/img1.jpg</image>
            <video/>
            <logic_part_tags>
              <part_tag>logic_part1</part_tag>
              <part_tag>logic_part2</part_tag>
            </logic_part_tags>
          </step>
          <step>
            <description>Step 2 instructions for the unit 1.</description>
           <image>img/img1.jpg</image>
            <video/>
            <logic_part_tags>
              <part_tag>logic_part1</part_tag>
              <part_tag>logic_part2</part_tag>
            </logic_part_tags>
          </step>
        </assembly_instruction>
        <test_instruction>
          <step>
            <description>Step 1 instructions on how to test the unit 1.</description>
            <image>img/img1.jpg</image>
            <video/>
            <logic_part_tags>
              <part_tag>logic_part1</part_tag>
              <part_tag>logic_part2</part_tag>
            </logic_part_tags>
          </step>
          <step>
            <description>Step 2 instructions on how to test the unit 1.</description>
            <image>img/img1.jpg</image>
            <video/>
            <logic_part_tags>
              <part_tag>logic_part1</part_tag>
              <part_tag>logic_part2</part_tag>
            </logic_part_tags>
          </step>
        </test_instruction>
        <user_manual>
          <step>
            <description>Step 1 in user manual on how to use unit 1.</description>
            <image>img/img1.jpg</image>
            <video/>
            <logic_part_tags>
              <part_tag>logic_part1</part_tag>
              <part_tag>logic_part2</part_tag>
            </logic_part_tags>
          </step>
          <step>
            <description>Step 2 in user manual on how to unit 1.</description>
            <image>img/img1.jpg</image>
            <video/>
            <logic_part_tags>
              <part_tag>logic_part1</part_tag>
              <part_tag>logic_part2</part_tag>
            </logic_part_tags>
          </step>
        </user_manual>
        <licensing>
          <description>Licensing for the unit 1.</description>
          <file>example.txt</file>
          <url>http://www.irnas.eu</url>
        </licensing>
        <safety>
          <description>Safety for the unit 1.</description>
          <file>example.txt</file>
          <url>http://www.irnas.eu</url>
        </safety>
        
        <children>
            <unit order="1">
                <name> UNIT1a</name>
                <description>
                  <abstract>
                    Very brief description of the first sub-unit (module).
                    </abstract>
