=== IRNAS/UsefulSource/troublemaker/instructions-schema.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" version="1">

  <xs:element name="instructions" type="typeInstructions"/>
  <xs:complexType name="typeInstructions">
     <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="description" type="xs:string"/>
            <xs:element name="parts" type="typeParts"/>
            <xs:element name="tools" type="typeTools"/>
            <xs:element name="video" type="typeVideo" minOccurs="0"/>
            <xs:element name="steps" type="typeSteps"/>
            <xs:element name="image" type="xs:normalizedString" minOccurs="0"/>
     </xs:sequence>
  </xs:complexType>
  
  <xs:complexType name="typeParts">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="part" type="typePart"  maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="order" type="xs:positiveInteger" use="required"/>
    </xs:complexType>
    <xs:complexType name="typePart">
        <xs:all>
            <xs:element name="module" type="xs:string"/>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="quantity" type="xs:string" minOccurs="0"/>
            <xs:element name="unit" type="xs:string" minOccurs="0"/>
        </xs:all>
        <xs:attribute name="order" type="xs:positiveInteger" use="required"/>
    </xs:complexType>
    
    <xs:complexType name="typeTools">
        <xs:sequence>
            <xs:element name="tool" type="typeTool"  maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="typeTool">
        <xs:all>
            <xs:element name="description" type="xs:string"/>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="price" type="xs:string" minOccurs="0"/>
            <xs:element name="image" type="xs:normalizedString" minOccurs="0"/>
            <xs:element name="url" type="xs:normalizedString" minOccurs="0"/>
        </xs:all>
        <xs:attribute name="order" type="xs:positiveInteger" use="required"/>
    </xs:complexType>
    
    <xs:complexType name="typeSteps">
        <xs:sequence>
            <xs:element name="step" type="typeStep"  maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="typeStep">
        <xs:all>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="sub_steps" type="typeSub_steps"/>

        </xs:all>
        <xs:attribute name="order" type="xs:positiveInteger" use="required"/>
    </xs:complexType>
    
    <xs:complexType name="typeSub_steps">
        <xs:sequence>
            <xs:element name="sub_step" type="typeSub_step"  maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="typeSub_step">
        <xs:all>
            <xs:element name="description" type="xs:string"/>
            <xs:element name="video" type="typeVideo" minOccurs="0"/>
            <xs:element name="image" type="xs:normalizedString" minOccurs="0"/>
            <xs:element name="step_parts" type="typeStep_parts" minOccurs="0"/>
        </xs:all>
        <xs:attribute name="order" type="xs:positiveInteger" use="required"/>
    </xs:complexType>
    
    <xs:complexType name="typeStep_parts">
        <xs:sequence>
            <xs:element name="step_part" type="typeStep_part"  maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="typeStep_part">
        <xs:all>
            <xs:element name="parts" type="xs:positiveInteger"/>
            <xs:element name="part" type="xs:positiveInteger"/>
            <xs:element name="quantity" type="xs:positiveInteger" minOccurs="0"/>
        </xs:all>
        <xs:attribute name="order" type="xs:positiveInteger" use="required"/>
    </xs:complexType>
    
    <xs:complexType name="typeVideo">
        <xs:all>
            <xs:element name="description" type="xs:token" minOccurs="0"/>
            <xs:element name="url" type="xs:normalizedString" minOccurs="0"/>
        </xs:all>
    </xs:complexType>


</xs:schema>

=== IRNAS/UsefulSource/troublemaker/instructions.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="instructions.xsl"?>
<instructions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="instructions-schema.xsd">
  <name>3-D TISKALNIK ULTIMAKER</name>
  <description>Navodila za sestavljanje tiskalnika Elektronik.si Ultimaker v 100 ali več korakih.</description>
  <image>img/printer2.jpg</image>
  
  <parts order="1">
  <name>Ohišje</name>
    <part order="1">
      <module>Ohišje</module>
      <name>Vezana plošča 6mm</name>
      <quantity>1,3</quantity>
      <unit>m^2</unit>
    </part>
    <part order="2">
      <module>Ohišje</module>
      <name>Vezana plošča 4mm</name>
      <quantity>0,1</quantity>
      <unit>m^2</unit>
    </part>
    <part order="3">
      <module>Ohišje</module>
      <name>Kompakt plošča 12mm</name>
      <quantity>0,25</quantity>
      <unit>m^2</unit>
    </part>
    <part order="4">
      <module>Ohišje</module>
      <name>Razrez</name>
      <quantity>1</quantity>
      <unit>kom</unit>
    </part>
  </parts>
  
  <parts order="2">
  <name>Vijaki</name>
    <part order="1">
      <module>Vijaki</module>
      <name>Vijak leč TORX M3 10mm BN6404</name>
      <quantity>80</quantity>
      <unit>kom</unit>
    </part>
    <part order="2">
      <module>Vijaki</module>
      <name>Vijak leč TORX M3 16mm BN6404</name>
      <quantity>100</quantity>
      <unit>kom</unit>
    </part>
    <part order="3">
      <module>Vijaki</module>
      <name>Vijak IMBUS M3 25mm DIN912</name>
      <quantity>30</quantity>
      <unit>kom</unit>
    </part>
    <part order="4">
      <module>Vijaki</module>
      <name>Vijak IMBUS M3 30mm DIN912</name>
      <quantity>50</quantity>
      <unit>kom</unit>
    </part>
    <part order="5">
      <module>Vijaki</module>
      <name>Vijak HEX M3 40mm DIN933</name>
      <quantity>10</quantity>
      <unit>kom</unit>
    </part>
    <part order="6">
      <module>Vijaki</module>
      <name>Vijak M4 10mm DIN7985</name>
      <quantity>4</quantity>
      <unit>kom</unit>
    </part>
    <part order="7">
      <module>Vijaki</module>
      <name>Vijak HEX M4 35mm DIN933</name>
      <quantity>5</quantity>
      <unit>kom</unit>
    </part>
    <part order="8">
      <module>Vijaki</module>
      <name>Vijak IMBUS M4 vgreznjena glava 30mm DIN7991</name>
      <quantity>3</quantity>
      <unit>kom</unit>
    </part>
    <part order="9">
      <module>Vijaki</module>
      <name>Vijak M4 50mm DIN7985</name>
      <quantity>2</quantity>
      <unit>kom</unit>
    </part>
    <part order="10">
      <module>Vijaki</module>
      <name>Podložka M3 velika 9mm premer DIN9021</name>
      <quantity>150</quantity>
      <unit>kom</unit>
    </part>
    <part order="11">
      <module>Vijaki</module>
      <name>Podložka M4 DIN125</name>
      <quantity>10</quantity>
      <unit>kom</unit>
    </part>
    <part order="12">
      <module>Vijaki</module>
      <name>Matica M3 4-roba DIN562</name>
      <quantity>100</quantity>
      <unit>kom</unit>
    </part>
    <part order="13">
      <module>Vijaki</module>
      <name>Matica M3 DIN934</name>
      <quantity>80</quantity>
      <unit>kom</unit>
    </part>
    <part order="14">
      <module>Vijaki</module>
      <name>Matica M4 DIN934</name>
      <quantity>10</quantity>
      <unit>kom</unit>
    </part>
    <part order="15">
      <module>Vijaki</module>
      <name>Krilata matica M4 DIN315</name>
      <quantity>3</quantity>
      <unit>kom</unit>
    </part>
    <part order="16">
      <module>Vijaki</module>
      <name>Vzmet 5mm premer, 12mm dolžina, 1mm žica</name>
      <quantity>5</quantity>
      <unit>kom</unit>
    </part>
  </parts>
  
  <parts order="3">
  <name>Vodila</name>
    <part order="1">
      <module>Vodila</module>
      <name>Vodilo okroglo W12 - 12mm x 409mm</name>
      <quantity>1</quantity>
      <unit>kom</unit>
    </part>
    <part order="2">
      <module>Vodila</module>
      <name>Vodilo okroglo W8 - 8mm x 337mm</name>
      <quantity>2</quantity>
      <unit>kom</unit>
    </part>
    <part order="3">
      <module>Vodila</module>
      <name>Vodilo okroglo W8 - 8mm x 348mm</name>
      <quantity>2</quantity>
      <unit>kom</unit>
    </part>
    <part order="4">
      <module>Vodila</module>
      <name>Vodilo okroglo W6 - 6mm x 265mm</name>
      <quantity>2</quantity>
      <unit>kom</unit>
    </part>
    <part order="5">
      <module>Vodila</module>
      <name>Trapezno vreteno Tr12x3 KUE 12 A R - 12mm x 390mm</name>
      <quantity>1</quantity>
      <unit>kom</unit>
    </part>
    <part order="6">
      <module>Vodila</module>
      <name>Matica trapezna C45</name>
      <quantity>1</quantity>
      <unit>kom</unit>
    </part>
    <part order="7">
      <module>Vodila</module>
      <name>Obdelava - postružen konec vretena na 8mm v dolžini 15mm</name>
      <quantity>1</quantity>
      <unit>kom</unit>
    </part>
    <part order="8">
      <module>Vodila</module>
      <name>Obdelava - porezkana okroglina na nasprotnih straneh trapezne matice, tako da je ta debela 25mm</name>
      <quantity>1</quantity>
      <unit>kom</unit>
    </part>
  </parts>
  
  <parts order="4">
  <name>Mehanika</name>
    <part order="1">
      <module>Mehanika</module>
      <name>GT2 jermenica 5mm os, 20 zob, 6mm širina</name>
      <quantity>2</quantity>
      <unit>kom</unit>
    </part>
     <part order="2">
      <module>Mehanika</module>
      <name>GT2 jermenica 8mm os, 20 zob, 6mm širina</name>
      <quantity>10</quantity>
      <unit>kom</unit>
    </part>
     <part order="3">
      <module>Mehanika</module>
      <name>GT2 100zob jermen 6mm</name>
      <quantity>2</quantity>
      <unit>kom</unit>
    </part>
     <part order="4">
      <module>Mehanika</module>
      <name>Opcija 1: GT2 308zob jermen (uporabi lesene dele za voziček z plitkim izrezom)</name>
      <quantity>4</quantity>
      <unit>kom</unit>
    </part>
     <part order="5">
      <module>Mehanika</module>
      <name>Opcija 2: GT2 308zob jermen (uporabi lesene dele za voziček z globokim izrezom)</name>
      <quantity>4</quantity>
      <unit>kom</unit>
    </part>
     <part order="6">
      <module>Mehanika</module>
      <name>Opcija 3: GT2 neskončen jermen (uporabi planetcnc natisnjene vozičke)</name>
      <quantity>2,5</quantity>
      <unit>m</unit>
    </part>
     <part order="7">
      <module>Mehanika</module>
      <name>Ležaj LM6UU</name>
      <quantity>4</quantity>
      <unit>kom</unit>
    </part>
     <part order="8">
      <module>Mehanika</module>
      <name>Ležaj LM12UU</name>
      <quantity>4</quantity>
      <unit>kom</unit>
    </part>
     <part order="9">
      <module>Mehanika</module>
      <name>Ležaj 688ZZ (8 x 16 x 5mm)</name>
      <quantity>8</quantity>
      <unit>kom</unit>
    </part>
     <part order="10">
      <module>Mehanika</module>
      <name>Ležaj 608ZZ (8 x 22 x 7mm)</name>
      <quantity>2</quantity>
      <unit>kom</unit>
    </part>
     <part order="11">
      <module>Mehanika</module>
      <name>Cnc sklopka 5mm na 8mm</name>
      <quantity>1</quantity>
      <unit>kom</unit>
    </part>
     <part order="12">
      <module>Mehanika</module>
      <name>Drsna puša SKF PCMF 081009.5 E</name>
      <quantity>8</quantity>
      <unit>kom</unit>
    </part>
  </parts>
  
  <parts order="5">
  <name>Elektronika</name>
    <part order="1">
      <module>Elektronika</module>
      <name>Krmilna elektronika (LCD,SD, bed, 2 extruders,..) - Marlin</name>
      <quantity>1</quantity>
      <unit>kom</unit>
    </part>
    <part order="2">
      <module>Elektronika</module>
      <name>Driverji za koračnike PoStep25-32</name>
      <quantity>4</quantity>
      <unit>kom</unit>
    </part>
    <part order="3">
      <module>Elektronika</module>
      <name>Koračni motorji NMEA17 (za osi X,Y,Z)</name>
      <quantity>3</quantity>
      <unit>kom</unit>
    </part>
    <part order="4">
      <module>Elektronika</module>
      <name>Napajalnik 24V 4.8A</name>
      <quantity>1</quantity>
      <unit>kom</unit>
    </part>
    <part order="5">
      <module>Elektronika</module>
      <name>Koračni motor z reduktorjem 14:1 (ekstruder)</name>
      <quantity>1</quantity>
      <unit>kom</unit>
    </part>
    <part order="6">
      <module>Elektronika</module>
      <name>Kabli (3m 0,75mm^2, 1,35m 16pin flat + IDC)</name>
      <quantity>1</quantity>
      <unit>kom</unit>
    </part>
    <part order="7">
      <module>Elektronika</module>
      <name>230V vtičnica s stikalom Multicomp JR-101-1-FRSG-02</name>
      <quantity>1</quantity>
      <unit>kom</unit>
    </part>
    <part order="8">
      <module>Elektronika</module>
      <name>Končno stikalo</name>
      <quantity>6</quantity>
      <unit>kom</unit>
    </part>
  </parts>
  
  <parts order="6">
  <name>Ekstruder in glava</name>
    <part order="1">
      <module>Ekstruder in glava</module>
      <name>E3D tiskalna glava 1.75mm bovden verzija</name>
      <quantity>1</quantity>
      <unit>kom</unit>
    </part>
    <part order="2">
      <module>Ekstruder in glava</module>
      <name>Push-fit pnevmatska spojka SQH 04 01s</name>
      <quantity>2</quantity>
      <unit>kom</unit>
    </part>
    <part order="3">
      <module>Ekstruder in glava</module>
      <name>Bovden 4mm zunaj 2mm znotraj 500mm dolžine</name>
      <quantity>1</quantity>
      <unit>kom</unit>
    </part>
    <part order="4">
      <module>Ekstruder in glava</module>
      <name>Ventilator 30x30mm 24V</name>
      <quantity>1</quantity>
      <unit>kom</unit>
    </part>
    <part order="5">
      <module>Ekstruder in glava</module>
      <name>Ventilator 40x40mm 24V</name>
      <quantity>1</quantity>
      <unit>kom</unit>
    </part>
    <part order="6">
      <module>Ekstruder in glava</module>
      <name>Lycy kabel 8žil (za tiskalno glavo)</name>
      <quantity>1,35</quantity>
      <unit>m</unit>
    </part>
